### ISSUE TITLE
Add strict from and until times verification in api

### ISSUE THREAD

**Issue by grzkv** [bookingcom/carbonapi#171] opened 2019-06-17 14:08 UTC
Currently, `api` accepts some times that are either too liberal or just incorrect. In this case,  the defaults are applied that either are not obvious or include timeframe that starts "at the beginning of time" (for Unix).

E.g.
```
http://localhost:8081/render?target=a.a.a&from=+5m (future)
http://localhost:8081/render?target=a.a.a&until=+5m (from implied to come since forever and into the future)
```
There are more similar cases.
 
This is closely related to #160

**Comment by grzkv** [comment] 2019-06-17 14:08
@KozzyKoder You may be interested in this one.

**Comment by azhiltsov** [comment] 2019-07-09 08:17
Also would be nice to prevent swap of from and until
from go-carbon logs:
Invalid time interval: from time '1562536741' is after until time '1561932061'
--

**Comment by bom-d-van** [comment] 2021-12-23 12:27
the issue is resolved by https://github.com/bookingcom/carbonapi/pull/200 and https://github.com/bookingcom/carbonapi/pull/341 now.

**Closed by bom-d-van** 2021-12-23 12:27 UTC
Labels: api
